//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : bitmap3D.h
//  @ Date : 2010/3/18
//  @ Author : 
//
//


#if !defined(_BITMAP3D_H)
#define _BITMAP3D_H

struct bitmap3D {
public:
	bitmap3D():pData(NULL){}
	bitmap3D(int ix, int iy, int iz):x(ix),y(iy),z(iz),pData(NULL){}
	int x;
	int y;
	int z;
	char* pData;
	int GetSize() {return x*y*z;}
};

#endif  //_BITMAP3D_H
