//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DWHistogram.cpp
//  @ Date : 2010/4/26
//  @ Author : 
//
//


#include "DWHistogram.h"


template <class T>
void DWHistogram<T>::addData( T* dst, int size, int step )
{
	for (int i=0;i<size;i+=step)
	{
		m_data->push_back(*(dst+i));
	}
	sort(m_data.begin(), m_data.end());
}
template <class T>
unsigned int DWHistogram<T>::size()
{
	return m_data->size();
}
template <class T>
double DWHistogram<T>::find( T key )
{
	unsigned int i = 0;
	for (Tvector::iterator it = m_data->begin();it != m_data->end();it++)
	{
		if (*it = key) break;
		i++;
	}   
	double p = m_data->size();
	p = i/p;
	return p;
}

template <class T>
void DWHistogram<T>::clear()
{
	m_data->clear();
}