	//

//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Color4.h
//  @ Date : 2010/3/18
//  @ Author :
//
//
#if !defined(_COLOR4_H)
#define _COLOR4_H
#pragma warning(disable : 4201)
#include <memory>
#endif //_COLOR4_H
