//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Textrue.cpp
//  @ Date : 2010/3/25
//  @ Author : 
//
//


#include "DW2DTexture.h"

int DW2DTexture::WriteIn(int gl_format, int gl_datatype, unsigned char* pData) {
	if (w<=0 || h<=0)
		return SIZE_ERROR;
	glGenTextures(1, &m_gltexture);
	glTexImage2D(GL_TEXTURE_2D, 0, 3, w, h, 0, gl_format, gl_datatype, pData);
	return TEXTURE_OK;
}


GLuint* DW2DTexture::UseGLTexture() {
	glBindTexture(GL_TEXTURE_2D,m_gltexture);
	return &m_gltexture;
}

