#pragma once

#include <vtkSmartPointer.h>
#include <vtkXMLPolyDataReader.h>
#include <vtkAppendPolyData.h>
#include <vtkClipPolyData.h>
#include <vtkCleanPolyData.h>
#include <vtkContourFilter.h>
#include <vtkFloatArray.h>
#include <vtkCellData.h>
#include <vtkPointData.h>
#include <vtkScalarsToColors.h>
#include <vtkLookupTable.h>
#include <vtkPolyDataMapper.h>
#include <vtkPolyData.h>
#include <vtkProperty.h>
#include <vtkActor.h>
#include <vtkPoints.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkVertexGlyphFilter.h>
#include <vtkFloatArray.h>
#include <vtkPolyDataPointSampler.h>
#include <vtkPolyDataToPolyDataFilter.h>
#include <vtkGraphLayoutFilter.h>
#include <vtkGeometryFilter.h>
#include <vtkMarchingContourFilter.h>
#include <vtkStructuredGridGeometryFilter.h>
#include <vtkStructuredGridOutlineFilter.h>
#include <vtkTransformPolyDataFilter.h>
#include <vtkMarchingCubes.h>
#include <vtkPolyDataConnectivityFilter.h>
#include <vtkUnstructuredGrid.h>
#include <vtkCellArray.h>
#include <vtkType.h>
#include <vtkGaussianSplatter.h>
#include <vtkSurfaceReconstructionFilter.h>
#include <vtkReverseSense.h>
#include <vtkDelaunay3D.h>
#include <vtkImageData.h>
#include <vtkElevationFilter.h>
#include <vtkBandedPolyDataContourFilter.h>
#include <vtkImageDataGeometryFilter.h>
#include <vtkTextureMapToPlane.h>
#include <vtkTriangleFilter.h>
#include <vtkDecimatePro.h>
#include <vtkLinearExtrusionFilter.h>
#include <vtkPlane.h>
#include <vtkCutter.h>
#include <vtkImageClip.h>
#include <vtkImageShrink3D.h>
#include <vtkVoxelContoursToSurfaceFilter.h>
#include <vtkOrientationMarkerWidget.h>
#include <vtkAxesActor.h>
#include <vtkDataSetSurfaceFilter.h>
#include <vtkStructuredGrid.h>
#include <vtkImagePlaneWidget.h>
#include <vtkVolume.h>
#include <vtkVolumeProperty.h>
#include <vtkSmartVolumeMapper.h>
#include <vtkPiecewiseFunction.h>
#include <vtkColorTransferFunction.h>
#include <vtkImageShiftScale.h>
#include <vtkDataArray.h>
#include <vtkCamera.h>
